---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
#LOAD LIBRARIES
library(flexdashboard)
library(tidyverse)
library(readxl)
library(rworldmap)
library(leaflet)
library(gridExtra)
library(broom)


#------LOAD FILES---------
CCodesfile="Country-Code.xlsx"
Zomatofile="zomato.xlsx"
CurrencyFile="CurrencyRates.xlsx"

CCodes=read_excel(CCodesfile) #importing country code file
zomato=read_excel(Zomatofile) #importing main zomato file
Currency=read_excel(CurrencyFile) #importing currency file

#------ GET RID OF SOME COLUMNS & ADD NEW ONES -------------
zomato1=zomato %>% select (-c(ID, Rating_Color,Switch_To_Order_Menu,Price_Range,Address,Locality_Verbose,Currency))
#we remove currency column as it is incorrect and contains too many unique symbols

#add in new columns: Country Names according to Country Code & proper currency names with conversion rates
zomato2 = zomato1 %>% left_join(CCodes) 
zomato3 = zomato2 %>% left_join(Currency) 

zomato3 %>% select(Currency, Country) #checking to see if country matched up with new currency values

#add in new column: USD Cost (for equal comparison)
zomato4 = zomato3 %>% mutate(Avg_Cost_USD = Average_Cost_For_Two*`Conversion Rate (USD)`) 
#Multiplied Currency Column by it's conversion rate

#replacing Cuisines col. with Principal_Cuisines (the first category of cuisines for every country row)
zomato5= zomato4 %>% separate(Cuisines,into=c("Principal_Cuisines")) #store "primary" cuisine types into new column and replace old with this

#we notice that there are several "0" rated stores for even expensive places so we decided to remove no rating stores

zomato5[zomato5 == 0] = NA #remove values that have zero
zomato5[zomato5 == "Not rated"] = NA #remove unrated values

zomato6 = zomato5 %>% mutate(Transformed_Rating = log10(Aggregate_Rating/(5-Aggregate_Rating)))

map.data = zomato6 %>% select(Country,Restaurant_Name,Longitude,Latitude)
zomato5 = zomato5 %>% mutate(Rating_Factor=ordered(Rating_Text,levels=c("Excellent","Very Good","Good","Average","Poor")))

India=map.data %>% filter(Country=="India")

```


### General World Map

```{r}
newmap = getMap(resolution = "li")
plot(newmap)
points(map.data$Longitude, map.data$Latitude, col = "red", cex = .6)
```

### Leaflet

```{r}
India %>% leaflet() %>% addTiles() %>%
  addMarkers(clusterOptions = markerClusterOptions()) %>%
  setView(78.9629,20,zoom=4)

```

### GGPLOT

```{r}
leaflet() %>%
  addTiles() %>%
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
```

